### ISSUE TITLE
App?

### ISSUE THREAD

**Issue by PhilChodrow** [jenelle99/PIC16BProject#2]
Hi team, this looks interesting but I can't find the source code for your app or a description of a place where I can interact with it!

**Comment by jenelle99** [comment]
Hi Professor, the app will open a new tab in your browser once you run the code in the FinalProject.py file. Let us know if that does not work. Thanks!

**Comment by PhilChodrow** [comment]
Confirmed! Please add explicit instructions in your new top-level `README.md` file, e.g.

1. Clone the app. 
2. Make sure that you've installed [packages]. 
3. Navigate in your terminal to ____. 
4. Run `command`. 
5. The app will open in the browser.

**Comment by jenelle99** [comment]
I just added that to our README file. Thank you for the feedback!
